### ISSUE TITLE
Doesnt appear to be scanning my RFID card

### ISSUE THREAD

**Issue by ERROR-404-NULL-NOT-FOUND** [MrJPGames/NFCReader#3]
I downloaded this to try and make a copy of my student id, but it just...doesnt detect it. Anyone know what the issue could be?

**Comment by MrJPGames** [comment]
This application only scans 0x4 UIDs, and thus if your student ID uses anything larger it will not work.

This is a really old very incomplete piece of software I wrote as a fun POC of interacting with generic RFID devices. As such I do not plan on improving it at this stage. You can try a mobile phone app if your phone supports NFC. Those tend to have support for far more devices (instead of being designed just to scan my old high school's RFID tag UIDs...)
